### ISSUE TITLE
The first issue

### ISSUE THREAD

**Issue by shofel** [shaun-mathew/Chameleon.nvim#1]
Hey! Thanks for your work. I have been thinking about this kind of plugin, but have never done it :)

I have tried this script, and it works :partying_face:

I would suggest some improvements
- [ ] turn it into a plugin so that anyone can install it which a plugin manager like Packer or Plug.vim
- [ ] when the script executed, assure the background color is set. That is, call `set_background` not only by autocmd, but also at the time when script loads
- [ ] when the user haven't got kitty`s remote control enabled, then handle the error and communicate to the user. Now it just crashes

What do you think of them? (:

**Comment by shaun-mathew** [comment]
I wasn't originally planning on making this a plugin, but I do see the value in it, so I'll turn it into one.
I'll fix the issues you've outlined there as well :).

**Comment by shofel** [comment]
I tried to fiddle with the script and struggled with kitty remote control. For some reason, even if remote control is enabled, the command is stuck :/ 

Finally I [ended up](https://github.com/shofel/dotfiles/blob/8f44f9ffb70babe9d18a6f8e054cc31b27706096/home-nix/flake.nix#L134) just appending the catppucin theme to my kitty config.

Thanks for the inspiration!

**Comment by shaun-mathew** [comment]
The blocking was due to using io.popen() which blocks neovim. Using vim's job api seems to have fixed the issue (c02bed28691b22007420ae06bd9d3cf582ad48f8). I've also added some error handling to check if there are any errors changing the background or getting the background. As for why it's getting stuck when remote control is enabled, I'm not sure. Perhaps you need to launch a new kitty instance and make sure that you aren't running in single-instance mode, or if you are try restarting said instance with remote control enabled.

Anyway, plugin feature is added (27d35fca229b8d41c4dffdb79ec3e2b231fe5176) as requested!
